#define MAX_CONNECTIONS 100
#define MAX_EVENTS 100
#define RPL_WELCOME 001
#define RPL_YOURHOST 002
#define ERR_NONICKNAMEGIVEN 431
#define ERR_ERRONEUSNICKNAME 432
#define ERR_ALREADYREGISTRED 462
#define ERR_NEEDMOREPARAMS 461

#define VERBOSE 0
#define DEBUG 0
#define LOOP 1